### ISSUE TITLE
Please archive this repository if no one at xing wants to maintain it

### ISSUE THREAD

**Issue by toy** [xing/rbenv-patchsets#10]
There are 3 unhandled pull requests and action is failing for several days sending notifications to me (AFAIU because I was the last to change the action). Could you please either archive the repository or at least disable the failing workflow? @skaes @0robustus1

**Comment by toy** [comment]
Maybe @furagu @JHK

**Comment by furagu** [comment]
I'm not a user of `rbenv` and never really worked on this repo. Maybe @skaes can help deciding how to address this?

**Comment by toy** [comment]
I already mentioned him in the issue and, as I didn't get any reply, pinging you guessing that you may have access to this repo. He is also not using rbenv (https://github.com/xing/rbenv-patchsets/pull/9#issuecomment-1025107768). I asked few times to ping in dev channel if someone can maintain this project, but no one seems to be interested and now I get a message about failed job every workday and wondering if I have reset the [60 days timer](https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow#:~:text=60%20days) by opening this issue.

**Comment by 0robustus1** [comment]
I disabled the actions for now and created a followup for @skaes.

**Comment by toy** [comment]
@0robustus1 Thank you!

**Comment by skaes** [comment]
There is no need to use railsexpress patches locally anymore. Therefore it does not make sense to maintain this.
